services:
  frontend:
    image: moboks/aeroport-frontend:v1
    ports:
      - "3000:80"
    networks:
      - aeroport-network

networks:
  aeroport-network:
    external: true
    name: ubuntu_aeroport-network